In [25]:
with open('One.txt') as f:
    words_one = f.read().lower().split()
    uni_words_one = set(words_one)

In [26]:
with open('Two.txt') as f:
    words_two = f.read().lower().split()
    uni_words_two = set(words_two)

In [27]:
all_uni_words = set()
all_uni_words.update(uni_words_one)
all_uni_words.update(uni_words_two)

In [28]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i+1

In [29]:
# Create an empty vector with space for each word in the vocabulary:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [30]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [31]:
# map the frequencies of each word in 1.txt to our vector:
with open('One.txt') as f:
    one_text = f.read().lower().split()
    
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind]+=1

In [32]:
one_freq

[1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0]

In [33]:
# Do the same for the second document:
with open('Two.txt') as f:
    two_text = f.read().lower().split()
    
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind]+=1
    

In [34]:
two_freq

[1, 2, 1, 1, 3, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1]

In [39]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind]=word

In [40]:
all_words

['a',
 'surfing',
 'sport',
 'this',
 'is',
 'are',
 'pets',
 'story',
 'animals',
 'catching',
 'fun',
 'water',
 'our',
 'canine',
 'about',
 'furry',
 'dogs',
 'waves',
 'popular']

In [41]:
import pandas as pd 

In [42]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

a  surfing  sport  this  is  are  pets  story  animals  catching  fun  \
0  1        0      0     1   1    1     1      1        1         0    0   
1  1        2      1     1   3    0     0      1        0         1    1   

   water  our  canine  about  furry  dogs  waves  popular  
0      0    1       1      1      1     2      0        0  
1      1    0       0      1      0     0      1        1

In [43]:
text = ['This is a line',
        "This is another line",
       "Completely different line"]

In [44]:
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer,CountVectorizer

In [46]:
cv = CountVectorizer()

In [47]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [48]:
sparse_mat = cv.fit_transform(text)

In [52]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [50]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [54]:
cv = CountVectorizer(stop_words='english')

In [55]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

In [56]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [58]:
tfidf_transformer = TfidfTransformer()

In [59]:
counts = cv.fit_transform(text)

In [60]:
counts

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [61]:
tfidf = tfidf_transformer.fit_transform(counts)

In [62]:
tfidf.todense()

matrix([[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.65249088, 0.65249088, 0.38537163]])

In [65]:
new = tfidf.fit_transform(text)

In [66]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])