In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("Advertising.csv")
X = df.drop('sales',axis=1)
y = df['sales']

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [10]:
poly_feature = polynomial_converter.fit_transform(X)

In [11]:
poly_feature.shape

(200, 19)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(poly_feature, y, test_size=0.30, random_state=101)

In [14]:
X_train.shape

(140, 19)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train = scaler.transform(X_train)

In [19]:
X_test = scaler.transform(X_test)

In [20]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
from sklearn.linear_model import Ridge


устанавливаем рандомный альфа парметр равный 10 

In [22]:
ridge_model = Ridge(alpha=10)


In [23]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [24]:
test_predictions = ridge_model.predict(X_test)

In [25]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [26]:
MAE = mean_absolute_error(y_test,test_predictions)

In [27]:
MAE

0.5774404204714183

In [28]:
RMSE= np.sqrt(mean_squared_error(y_test,test_predictions))

In [29]:
RMSE

0.8946386461319674

In [30]:
from sklearn.linear_model import RidgeCV

запускаем одну и ту же можель с целью проверить как измениться эффетивность модели в зависимости от показателя Лямда(в коде aphas)

In [31]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10.0), scoring='neg_mean_squared_error')

В данном случае даем на выбор 3 парметра альфа чтобы система нашла наибольшицй показатель


In [32]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [33]:
ridge_cv_model.alpha_

0.1

In [34]:
from sklearn.metrics import SCORERS

In [35]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [36]:
test_predictions = ridge_cv_model.predict(X_test)

In [37]:
MAE = mean_absolute_error(y_test,test_predictions)

In [38]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [39]:
MAE

0.4273774884342038

In [40]:
RMSE

0.6180719926951576

In [41]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [42]:
ridge_cv_model.best_score_

-0.3777066848707357

In [45]:
from sklearn.linear_model import LassoCV

In [48]:
lasss_cv_model = LassoCV(eps=0.1, n_alphas = 100, cv=5, max_iter=10000000)

In [49]:
lasss_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1, max_iter=10000000)

In [50]:
lasss_cv_model.alpha_

0.4943070909225828

In [51]:
test_predictions=lasss_cv_model.predict(X_test)

In [52]:
MAE = mean_absolute_error(y_test,test_predictions)

In [53]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [54]:
MAE

0.6541723161252856

In [55]:
RMSE

1.130800102276254

In [56]:
lasss_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [57]:
from sklearn.linear_model import ElasticNetCV

ELasticNET позволяет получить преимущество прошлых регуляризаций путем усреднения их работы 

в качестве аргумента l1_ratio = передается коэфициент насколько больше лассо или редж регрессии будет в финальной моделе) 

In [58]:
elastik_model = ElasticNetCV(l1_ratio=[.1, .5, .7,
        .9, .95, .99, 1],eps=0.001,n_alphas=100, max_iter=1000000)

In [59]:
elastik_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [62]:
elastik_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [63]:
elastik_model.alpha_

0.004943070909225827

In [65]:
test_predictions = elastik_model.predict(X_test)

In [66]:
MAE = mean_absolute_error(y_test,test_predictions)

Эластик нет решает какую из регуляций взять и если однозначного отввета нет то определяет пропорции в которых используется каждый из видов регуляций 

In [67]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))