In [2]:
my_list=[1,2,3,1]
    

In [1]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3, 1])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [28]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [4]:
np.random.rand(10)

array([0.3941359 , 0.47353268, 0.6459884 , 0.68901609, 0.97598483,
       0.51425373, 0.96819557, 0.49134248, 0.87262817, 0.50694502])

In [36]:
np.random.randn(4,4)


array([[-0.84558527,  0.24037084,  0.60149809,  0.39446658],
       [ 1.64366258, -0.37968102,  0.45265106, -0.68103286],
       [ 0.7047324 , -1.12904194, -0.4280213 ,  0.88003353],
       [-1.22993669, -1.27051375,  0.46253227,  0.49987691]])

In [45]:
np.random.randint(1,100,10)

array([46, 96, 58, 36, 90, 55, 39, 89, 64, 35])

In [46]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr = np.random.randint(0,50,10)

In [49]:
ranarr

array([40, 46, 46, 28, 39,  9, 35, 28,  5, 18])

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr

array([40, 46, 46, 28, 39,  9, 35, 28,  5, 18])

In [53]:
ranarr.max()

46

In [54]:
arr.shape


(25,)

In [64]:
arr=arr.reshape(5,5)

In [65]:
arr.shape

(5, 5)

In [66]:
arr.dtype

dtype('int64')