In [2]:
import numpy as np 


In [4]:
arr = np.arange(0,11)

In [5]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [8]:
arr[0:3]

array([0, 1, 2])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[2][1]

40

In [40]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [42]:
arr_2d[:3,1:2]

array([[10],
       [25],
       [40]])

In [43]:
arr = np.arange(1,11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
bool_array = arr > 5

In [49]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr<3]

array([1, 2])

In [51]:
arr_2d= np.arange(50).reshape(5,10)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
arr_2d[3:4,1:]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39]])