In [2]:
import numpy as np 

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr/arr

/var/folders/8d/wwwj4v6n7h1db0y82bcw5d500000gn/T/ipykernel_90746/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
a = [1]
b=[2]
c=a|b
print(c)

TypeError: unsupported operand type(s) for |: 'list' and 'list'